# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-11 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infraccion',
            fields=[
                ('nro_alta', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('inspector', models.CharField(max_length=50)),
                ('infractor', models.CharField(max_length=50)),
                ('dominio', models.CharField(max_length=15)),
                ('descripcion', models.CharField(max_length=50)),
                ('clase_vehiculo', models.CharField(choices=[(b'A', 'Ciclomotores y Motocicletas'), (b'B', 'Automoviles'), (b'C', 'Camiones'), (b'D', 'Vehiculos de Servicios'), (b'E', 'Camiones Articulados'), (b'F', 'Automotores Descripcion discapacidad'), (b'G', 'Maquinaria Agricola')], max_length=50)),
            ],
        ),
    ]
